### ISSUE TITLE
1.24 fails to build on macOS 10.5.8: `listing.c: error: ‘const struct stat’ has no member named ‘st_birthtimespec’`

### ISSUE THREAD

**Issue by barracuda156** [leo-arch/CliFM#335]
**Describe the bug**
Build fails on Leopard:
```
[ 45%] Building C object CMakeFiles/clifm.dir/src/listing.c.o
/usr/bin/gcc-4.2 -DCLIFM_DATADIR=/opt/local/share -I/opt/local/include -pipe -Os -DCLIFM_LEGACY -std=c99 -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -arch ppc64 -mmacosx-version-min=10.5 -MD -MT CMakeFiles/clifm.dir/src/listing.c.o -MF CMakeFiles/clifm.dir/src/listing.c.o.d -o CMakeFiles/clifm.dir/src/listing.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c: In function ‘set_long_attribs’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:947: error: ‘const struct stat’ has no member named ‘st_birthtimespec’
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c: In function ‘compute_maxes’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c: In function ‘load_file_gral_info’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:2946: error: ‘const struct stat’ has no member named ‘st_birthtimespec’
make[2]: *** [CMakeFiles/clifm.dir/src/listing.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/build'
make[1]: *** [CMakeFiles/clifm.dir/all] Error 2
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/build'
make: *** [all] Error 2
```

**To Reproduce**
Run the build on macOS 10.5.8.

**Expected behavior**
It would be nice if it compiles.

**Desktop (please complete the following information):**
 - OS: macOS
 - Clifm version: 1.24
- Installation source: Tarball from here via MacPorts.

**Additional context**
This was not found out earlier, because I only used 10.6 on powerpc, and there `st_birthtimespec` is supported, from what it looks, at least in 10.6.8.

**Comment by barracuda156** [comment]
@leo-arch Could you say how this macro is set? https://github.com/leo-arch/clifm/blob/66e5d7789fff84de426da130162b11478295241c/src/listing.c#L2942C13-L2942C21
Perhaps it should just not be defined on < 10.6.

**Comment by barracuda156** [comment]
Nevermind, I know the fix, gimme a minute.
