### ISSUE TITLE
Doesn't build on OpenBSD 6.9 i386

### ISSUE THREAD

**Issue by ffuentese** [leo-arch/clifm#42]
**Describe the bug**
Can't compile clifm in OpenBSD i386 version 6.9 due to readline error:

```
$ doas make install       
Detected operating system: OpenBSD
cc -o clifm src/*.c -O2 -pipe   -I/usr/local/include -L/usr/local/lib -lereadline -lintl
In file included from src/keybinds.c:30:
/usr/local/include/ereadline/readline/readline.h:677:8: error: unknown type name
      'rl_cpvfunc_t'
extern rl_cpvfunc_t *rl_completion_word_break_hook;
       ^
1 error generated.
*** Error 1 in /home/ffuentes/clifm (Makefile:33 'build')

```

**To Reproduce**
1. git clone the project and cd to it
2. doas make install

**Expected behavior**

The program is installed.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OpenBSD]
 - Program version [git version]
 - Shell [ksh]
 - Terminal [sakura]
 - Version [3.7.1]

**Additional context**

**Comment by leo-arch** [comment]
Hi @ffuentese. Thanks for notifying this bug. I have implemented a very dirty workaround, but it should work while we find and solved the issue in an appropriate way. Clone the repo again and recompile.

Please let us know if it works for you.

**Comment by ffuentese** [comment]
> Hi @ffuentese. Thanks for notifying this bug. I have implemented a very dirty workaround, but it should work while we find and solved the issue in an appropriate way. Clone the repo again and recompile.
> 
> Please let us know if it works for you.

It works!

**Comment by leo-arch** [comment]
Great! Closing.
