### PR TITLE
helpers.h: no st_birthtimespec on macOS ppc64

### LINKED ISSUE #335: 1.24 fails to build on macOS 10.5.8: `listing.c: error: ‘const struct stat’ has no member named ‘st_birthtimespec’`
**Describe the bug**
Build fails on Leopard:
```
[ 45%] Building C object CMakeFiles/clifm.dir/src/listing.c.o
/usr/bin/gcc-4.2 -DCLIFM_DATADIR=/opt/local/share -I/opt/local/include -pipe -Os -DCLIFM_LEGACY -std=c99 -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -arch ppc64 -mmacosx-version-min=10.5 -MD -MT CMakeFiles/clifm.dir/src/listing.c.o -MF CMakeFiles/clifm.dir/src/listing.c.o.d -o CMakeFiles/clifm.dir/src/listing.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c: In function ‘set_long_attribs’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:947: error: ‘const struct stat’ has no member named ‘st_birthtimespec’
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c: In function ‘compute_maxes’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:1057: warning: comparison is always true due to limited range of data type
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c: In function ‘load_file_gral_info’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/clifm-1.24/src/listing.c:2946: error: ‘const struct stat’ has no member named ‘st_birthtimespec’
make[2]: *** [CMakeFiles/clifm.dir/src/listing.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/build'
make[1]: *** [CMakeFiles/clifm.dir/all] Error 2
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_sysutils_clifm/clifm/work/build'
make: *** [all] Error 2
```

**To Reproduce**
Run the build on macOS 10.5.8.

**Expected behavior**
It would be nice if it compiles.

**Desktop (please complete the following information):**
 - OS: macOS
 - Clifm version: 1.24
- Installation source: Tarball from here via MacPorts.

**Additional context**
This was not found out earlier, because I only used 10.6 on powerpc, and there `st_birthtimespec` is supported, from what it looks, at least in 10.6.8.

### PR DESCRIPTION
**Pull request by barracuda156**
Closes: https://github.com/leo-arch/clifm/issues/335

Making a draft, since I wanna verify the status on 10.6.8 32-bit. If somehow macOS defines that even on 32-bit, then the appropriate condition should be < 10.6.
(But there is no support for ppc64 in 10.6, so it is always 10.5 or 10.4.)

### CODE REVIEW

**Comment by barracuda156** [comment]
Okay, st_birthtimespec does work fine in 10.6.8 powerpc (32-bit) but did not work in 10a190 build of 10.6 earlier. However I think there is little sense to care about 10a190, once we have a newer version.
On Leopard st_birthtimespec is missing, even on 64-bit.

I think I should switch the macro to macOS version-based condition rather than bitness.

**Comment by leo-arch** [comment]
Hi @barracuda156. According to the [documentation](https://developer.apple.com/documentation/kernel/stat64/1493635-st_birthtimespec), the `st_birthtimespec` member is available only since 10.6 (it does not mention any specific architecture, so I guess it applies to all architectures).

So yes, a version based check seems more accurate:
```c
...
#elif defined(__NetBSD__)
# define ST_BTIME st_birthtimespec
#elif defined(__APPLE__)
# include <AvailabilityMacros.h>
# if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_6
#  define ST_BTIME st_birthtimespec
# endif
...
#endif
```

Could you give this a try? I'm not sure `AvailabilityMacros.h` exist before High Sierra (10.13) (I don't see any error regarding this header in your [build logs](https://github.com/leo-arch/clifm/issues/335#issue-3006904578), so that it is probably provided by `LegacySupport`). If not, we may need to fallback to the architecture check.

**Comment by barracuda156** [comment]
Ok, cool, I will switch to that. `AvailabilityMacros.h` work at least back to Tiger, as I recall. Something else like `TargetConditonals` (?) may be missing in early systems.

**Comment by leo-arch** [comment]
Great. Please give this a shot and let me know if it works as expected. If it does, update this PR so it can be merged.

**Comment by barracuda156** [comment]
@leo-arch If you don’t mind, I used the explicit numeric comparison: `MAC_OS_X_VERSION_10_6` is not defined prior to 10.6, so the condition will always be true, which is not what we need.

**Comment by leo-arch** [comment]
Thanks @barracuda156!
